### PR TITLE
Fix Azure support: now keys are base64 encoded

### PR DESCRIPTION
**Pull request by GrahamCampbell**
Closes #48. Ping @dmoreno and @smskin.

### CODE REVIEW

**Comment by dmoreno** [comment]
Now, Azure gives you keys encoded as base64 string. This was detected and fixed in GrahamCampbell/Laravel-Flysystem#48. But that PR is not mergeable because it breaks tests.

I picked the fix and I added some more fixes to AzureConnectorTest.php to avoid breaking the tests.

**Comment by GrahamCampbell** [comment]
Thanks. Are you ok for me to merge this then?

**Comment by dmoreno** [comment]
I think #53 is complete: fix + tests.

**Comment by GrahamCampbell** [comment]
Great. Merging. :)

**Comment by GrahamCampbell** [comment]
Thank you. :)

**Comment by dmoreno** [comment]
You're welcome! Your work with Laravel is great! ;-)

**Comment by GrahamCampbell** [comment]
No problem. I'll be tagging a new release for this package in a few mins to include this fix. :)

**Pull request merged**
